import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className="fixed top-0 left-0 right-0 bg-fixed bg-cover bg-center min-h-screen"
         style={{backgroundImage: `url("/background.png")`}}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href={"/favicon.ico"}/>
      </Head>
      <main className="fixed flex md:block px-6 md:pl-64 pt-48">
        <div className="flex flex-col text-white md:w-80 tracking-widest">
          <div className="h-12 w-12 relative rounded-full mb-4">
            <Image layout="fill" alt="Logo" src="/GitHub-White.png"/>
          </div>
          <div>
            <p className="text-5xl font-extrabold uppercase">
              Github repositories manager
            </p>
          </div>
          <div>
            <p className="text-sm uppercase">
              Find all your favorite projects in one place.
            </p>
          </div>
          <div className="mt-8">
            <Link href={"/dashboard"}>
              <a className="px-4 py-3 rounded-md text-lg cursor-pointer transition duration-400 ease-in-out bg-blue-600 hover:bg-purple-600 transform hover:-translate-y-1 hover:scale-110">
                Go to dashboard
              </a>
            </Link>
          </div>
        </div>
      </main>
      <footer>
        
      </footer>
    </div>
  )
}

export default Home
